# Nutrition Analysis Tour
## Action: Relational database creation
## Language/tool: Python Pandas & PostgreSQL
---

### PART 1: Assign ID numbers to "category" and "name" groups
---

In [1]:
import pandas as pd

In [2]:
# Bring up cleaned data set
sb_rel_db = pd.read_csv("sb_clean.csv")
sb_rel_db.head()

,category,name,size_oz,milk_type,calories,calories_%dv,caffeine_mg,caffeine_%dv,total_fat_g,fat_%dv,...,carbs_g,chol_mg,fiber_g,sugars_g,sugars_%dv,protein_g,vit_a_%dv,vit_c_%dv,calcium_%dv,iron_%dv
0,Classic Espresso Drinks,Caffè Latte,8,Nonfat,70,4.0,75,19.0,0.0,0.0,...,75,10,0,9,18.0,6.0,10,0,20,0
1,Classic Espresso Drinks,Caffè Latte,8,2%,100,5.0,75,19.0,4.0,4.0,...,85,10,0,9,18.0,6.0,10,0,20,0
2,Classic Espresso Drinks,Caffè Latte,8,Soy,70,4.0,75,19.0,2.0,3.0,...,65,6,1,4,8.0,5.0,6,0,20,8
3,Classic Espresso Drinks,Caffè Latte,12,Nonfat,100,5.0,75,19.0,0.0,0.0,...,120,15,0,14,28.0,10.0,15,0,30,0
4,Classic Espresso Drinks,Caffè Latte,12,2%,150,8.0,75,19.0,6.0,8.0,...,135,15,0,14,28.0,10.0,15,0,30,0

In [3]:
# Add placeholder column for category index numbers
sb_rel_db["cat_id"] = sb_rel_db.index + 1
sb_rel_db.head()

,category,name,size_oz,milk_type,calories,calories_%dv,caffeine_mg,caffeine_%dv,total_fat_g,fat_%dv,...,chol_mg,fiber_g,sugars_g,sugars_%dv,protein_g,vit_a_%dv,vit_c_%dv,calcium_%dv,iron_%dv,cat_id
0,Classic Espresso Drinks,Caffè Latte,8,Nonfat,70,4.0,75,19.0,0.0,0.0,...,10,0,9,18.0,6.0,10,0,20,0,1
1,Classic Espresso Drinks,Caffè Latte,8,2%,100,5.0,75,19.0,4.0,4.0,...,10,0,9,18.0,6.0,10,0,20,0,2
2,Classic Espresso Drinks,Caffè Latte,8,Soy,70,4.0,75,19.0,2.0,3.0,...,6,1,4,8.0,5.0,6,0,20,8,3
3,Classic Espresso Drinks,Caffè Latte,12,Nonfat,100,5.0,75,19.0,0.0,0.0,...,15,0,14,28.0,10.0,15,0,30,0,4
4,Classic Espresso Drinks,Caffè Latte,12,2%,150,8.0,75,19.0,6.0,8.0,...,15,0,14,28.0,10.0,15,0,30,0,5

In [4]:
# Group dataframe by category
cat_groups = sb_rel_db.groupby("category")

# Establish unique counter start for category groups
counter = 1000
# Iterate through 'category' groups and assign each one a unique, incremental number
for item in cat_groups.groups.keys():
    sb_rel_db.loc[sb_rel_db["category"] == item, ["cat_id"]] = counter
    counter +=1
sb_rel_db["cat_id"].value_counts()

1000    56
1006    40
1008    36
1002    36
1005    13
1003    13
1004    12
1007     9
1001     4
Name: cat_id, dtype: int64

---
##### ISSUE: in the name column, "Coffee" is used by 2 different categories (Frappuccino Light Blended Coffee and Frappuccino Blended Coffee). This will cause non-unique name values.  

##### SOLUTION: create name "Coffee Lite" for category Frappuccino Light Blended Coffee

In [5]:
# Find index numbers of values we wish to amend
to_fix = sb_rel_db[sb_rel_db.category == "Frappuccino® Light Blended Coffee"] # returns dataframe with index #s 196, 197, 198 having the name "Coffee"

# Amend located rows' name from "Coffee" to "Coffee Lite"
sb_rel_db.loc[[196, 197, 198], ["name"]] = "Coffee Lite"
sb_rel_db.loc[[196, 197, 198]]

,category,name,size_oz,milk_type,calories,calories_%dv,caffeine_mg,caffeine_%dv,total_fat_g,fat_%dv,...,chol_mg,fiber_g,sugars_g,sugars_%dv,protein_g,vit_a_%dv,vit_c_%dv,calcium_%dv,iron_%dv,cat_id
196,Frappuccino® Light Blended Coffee,Coffee Lite,12,Nonfat,90,4.0,70,18.0,0.0,0.0,...,20,0,19,38.0,3.0,4,0,10,0,1004
197,Frappuccino® Light Blended Coffee,Coffee Lite,16,Nonfat,120,6.0,95,24.0,0.0,0.0,...,26,0,26,52.0,3.0,6,0,10,0,1004
198,Frappuccino® Light Blended Coffee,Coffee Lite,20,Nonfat,160,8.0,120,30.0,0.0,0.0,...,34,0,33,66.0,5.0,8,0,15,2,1004

In [6]:
# Add placeholder column for name index numbers
sb_rel_db["name_id"] = sb_rel_db.index + 1
sb_rel_db.head()

,category,name,size_oz,milk_type,calories,calories_%dv,caffeine_mg,caffeine_%dv,total_fat_g,fat_%dv,...,fiber_g,sugars_g,sugars_%dv,protein_g,vit_a_%dv,vit_c_%dv,calcium_%dv,iron_%dv,cat_id,name_id
0,Classic Espresso Drinks,Caffè Latte,8,Nonfat,70,4.0,75,19.0,0.0,0.0,...,0,9,18.0,6.0,10,0,20,0,1000,1
1,Classic Espresso Drinks,Caffè Latte,8,2%,100,5.0,75,19.0,4.0,4.0,...,0,9,18.0,6.0,10,0,20,0,1000,2
2,Classic Espresso Drinks,Caffè Latte,8,Soy,70,4.0,75,19.0,2.0,3.0,...,1,4,8.0,5.0,6,0,20,8,1000,3
3,Classic Espresso Drinks,Caffè Latte,12,Nonfat,100,5.0,75,19.0,0.0,0.0,...,0,14,28.0,10.0,15,0,30,0,1000,4
4,Classic Espresso Drinks,Caffè Latte,12,2%,150,8.0,75,19.0,6.0,8.0,...,0,14,28.0,10.0,15,0,30,0,1000,5

In [7]:
# Group dataframe by name column
name_groups = sb_rel_db.groupby("name")

# Establish unique counter start for category groups
counter = 2000
# Iterate through 'name' groups and assign each one a unique, incremental number
for item in name_groups.groups.keys():
    sb_rel_db.loc[sb_rel_db["name"] == item, ["name_id"]] = counter
    counter +=1

---
### PART 2: Create relational tables & export as .csv files
---

In [8]:
cat_table = sb_rel_db.filter(["cat_id", "category"], axis = 1)
cat_table = cat_table.drop_duplicates().sort_values("cat_id")
cat_table.to_csv('cat_table.csv', index = False)

name_table = sb_rel_db.filter(["name_id", "cat_id", "name"], axis = 1)
name_table = name_table.drop_duplicates().sort_values("name_id")
name_table.to_csv('name_table.csv', index = False)

coffee_table = sb_rel_db.filter(["name_id", "size_oz", "milk_type", "calories_%dv", "caffeine_%dv", "fat_%dv", "sugars_%dv"], axis = 1) # couldn't resist "coffee_table" name
coffee_table.to_csv('coffee_table.csv', index = False)

In [9]:
# Verify that unique name_ids do not appear for multiple categories
name_table

     name_id  cat_id                                             name
129     2000    1007                        Banana Chocolate Smoothie
187     2001    1001                                    Brewed Coffee
191     2002    1000                                  Caffè Americano
0       2003    1000                                      Caffè Latte
12      2004    1000              Caffè Mocha (Without Whipped Cream)
36      2005    1000                                       Cappuccino
202     2006    1004                                          Caramel
156     2007    1002                  Caramel (Without Whipped Cream)
212     2008    1006      Caramel Apple Spice (Without Whipped Cream)
48      2009    1006                                Caramel Macchiato
138     2010    1002                                           Coffee
196     2011    1004                                      Coffee Lite
72      2012    1006            Hot Chocolate (Without Whipped Cream)
216     2013    1005          Iced Brewed Coffee (With Classic Syrup)
120     2014    1005   Iced Brewed Coffee (With Milk & Classic Syrup)
205     2015    1004                                        Java Chip
165     2016    1002                Java Chip (Without Whipped Cream)
199     2017    1004                                            Mocha
147     2018    1002                    Mocha (Without Whipped Cream)
132     2019    1007                     Orange Mango Banana Smoothie
195     2020    1005       Shaken Iced Tazo® Tea (With Classic Syrup)
208     2021    1000                       Skinny Latte (Any Flavour)
174     2022    1003     Strawberries & Crème (Without Whipped Cream)
135     2023    1007                       Strawberry Banana Smoothie
84      2024    1008                             Tazo® Chai Tea Latte
108     2025    1008  Tazo® Full-Leaf Red Tea Latte (Vanilla Rooibos)
96      2026    1008                            Tazo® Green Tea Latte
183     2027    1003             Vanilla Bean (Without Whipped Cream)
24      2028    1000         Vanilla Latte (Or Other Flavoured Latte)
60      2029    1006    White Chocolate Mocha (Without Whipped Cream)

---
### PART 3: Set up schemas, keys with PostgreSQL
---

```sql
DROP TABLE if exists cat_table;
DROP TABLE if exists name_table;
DROP TABLE if exists prep_table;
DROP TABLE if exists nutr_table;
```

```sql
CREATE TABLE cat_table (
cat_id INT PRIMARY KEY,
category VARCHAR (60)
);
```

```sql
CREATE TABLE name_table (
name_id INT PRIMARY KEY,
cat_id SMALLINT,
name VARCHAR (60),
FOREIGN KEY (cat_id) REFERENCES cat_table (cat_id)
);
```

```sql
CREATE TABLE coffee_table (
id SERIAL PRIMARY KEY,
name_id SMALLINT,
size_oz SMALLINT,
milk_type VARCHAR (60),
calories_perc_dv FLOAT,
caffeine_perc_dv FLOAT,
fat_perc_dv FLOAT,
sugars_perc_dv FLOAT,
FOREIGN KEY (name_id) REFERENCES name_table (name_id)
);
```

---
### PART 4: Import .csv files with PostgreSQL
---
#### Data from the prepared .csv files was imported via the pgAdmin4 Import command
#### Entity-Relationship Diagram:

![alt text](sb_erd.png "Title")