In [1]:
import pandas as pd

In [2]:
sb_rel_db = pd.read_csv("sb_clean.csv")
sb_rel_db.head()

,category,name,size_oz,milk_type,calories,calories_%dv,caffeine_mg,caffeine_%dv,total_fat_g,fat_%dv,...,carbs_g,chol_mg,fiber_g,sugars_g,sugars_%dv,protein_g,vit_a_%dv,vit_c_%dv,calcium_%dv,iron_%dv
0,Classic Espresso Drinks,Caffè Latte,8,Nonfat,70,4.0,75,19.0,0.0,0.0,...,75,10,0,9,18.0,6.0,10,0,20,0
1,Classic Espresso Drinks,Caffè Latte,8,2%,100,5.0,75,19.0,4.0,4.0,...,85,10,0,9,18.0,6.0,10,0,20,0
2,Classic Espresso Drinks,Caffè Latte,8,Soy,70,4.0,75,19.0,2.0,3.0,...,65,6,1,4,8.0,5.0,6,0,20,8
3,Classic Espresso Drinks,Caffè Latte,12,Nonfat,100,5.0,75,19.0,0.0,0.0,...,120,15,0,14,28.0,10.0,15,0,30,0
4,Classic Espresso Drinks,Caffè Latte,12,2%,150,8.0,75,19.0,6.0,8.0,...,135,15,0,14,28.0,10.0,15,0,30,0

In [3]:
# Add placeholder column for category index numbers
sb_rel_db["cat_id"] = sb_rel_db.index + 1
sb_rel_db

,category,name,size_oz,milk_type,calories,calories_%dv,caffeine_mg,caffeine_%dv,total_fat_g,fat_%dv,...,chol_mg,fiber_g,sugars_g,sugars_%dv,protein_g,vit_a_%dv,vit_c_%dv,calcium_%dv,iron_%dv,cat_id
0,Classic Espresso Drinks,Caffè Latte,8,Nonfat,70,4.0,75,19.0,0.0,0.0,...,10,0,9,18.0,6.0,10,0,20,0,1
1,Classic Espresso Drinks,Caffè Latte,8,2%,100,5.0,75,19.0,4.0,4.0,...,10,0,9,18.0,6.0,10,0,20,0,2
2,Classic Espresso Drinks,Caffè Latte,8,Soy,70,4.0,75,19.0,2.0,3.0,...,6,1,4,8.0,5.0,6,0,20,8,3
3,Classic Espresso Drinks,Caffè Latte,12,Nonfat,100,5.0,75,19.0,0.0,0.0,...,15,0,14,28.0,10.0,15,0,30,0,4
4,Classic Espresso Drinks,Caffè Latte,12,2%,150,8.0,75,19.0,6.0,8.0,...,15,0,14,28.0,10.0,15,0,30,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Signature Espresso Drinks,Caramel Apple Spice (Without Whipped Cream),16,NaN,280,14.0,0,0.0,0.0,0.0,...,70,0,65,130.0,0.0,0,0,0,0,215
215,Signature Espresso Drinks,Caramel Apple Spice (Without Whipped Cream),20,NaN,360,18.0,0,0.0,0.0,0.0,...,89,0,83,166.0,0.0,0,0,0,0,216
216,Shaken Iced Beverages,Iced Brewed Coffee (With Classic Syrup),12,NaN,60,3.0,120,30.0,0.0,0.0,...,15,0,15,30.0,0.0,0,0,0,0,217
217,Shaken Iced Beverages,Iced Brewed Coffee (With Classic Syrup),16,NaN,90,4.0,165,41.0,0.0,0.0,...,21,0,21,42.0,0.0,0,0,0,0,218
218,Shaken Iced Beverages,Iced Brewed Coffee (With Classic Syrup),20,NaN,130,6.0,235,59.0,0.0,0.0,...,31,0,31,62.0,0.0,0,0,0,0,219

In [4]:
# Group dataframe by category
cat_groups = sb_rel_db.groupby("category")

# Establish unique counter start for category groups
counter = 1000
# Iterate through 'category' groups and assign each one a unique, incremental number
for item in cat_groups.groups.keys():
    sb_rel_db.loc[sb_rel_db["category"] == item, ["cat_id"]] = counter
    counter +=1
sb_rel_db["cat_id"].value_counts()

1000    56
1006    40
1008    36
1002    36
1005    13
1003    13
1004    12
1007     9
1001     4
Name: cat_id, dtype: int64

In [5]:
# Add placeholder column for name index numbers
sb_rel_db["name_id"] = sb_rel_db.index + 1
sb_rel_db.head()

,category,name,size_oz,milk_type,calories,calories_%dv,caffeine_mg,caffeine_%dv,total_fat_g,fat_%dv,...,fiber_g,sugars_g,sugars_%dv,protein_g,vit_a_%dv,vit_c_%dv,calcium_%dv,iron_%dv,cat_id,name_id
0,Classic Espresso Drinks,Caffè Latte,8,Nonfat,70,4.0,75,19.0,0.0,0.0,...,0,9,18.0,6.0,10,0,20,0,1000,1
1,Classic Espresso Drinks,Caffè Latte,8,2%,100,5.0,75,19.0,4.0,4.0,...,0,9,18.0,6.0,10,0,20,0,1000,2
2,Classic Espresso Drinks,Caffè Latte,8,Soy,70,4.0,75,19.0,2.0,3.0,...,1,4,8.0,5.0,6,0,20,8,1000,3
3,Classic Espresso Drinks,Caffè Latte,12,Nonfat,100,5.0,75,19.0,0.0,0.0,...,0,14,28.0,10.0,15,0,30,0,1000,4
4,Classic Espresso Drinks,Caffè Latte,12,2%,150,8.0,75,19.0,6.0,8.0,...,0,14,28.0,10.0,15,0,30,0,1000,5

In [6]:
# Group dataframe by name
name_groups = sb_rel_db.groupby("name")

# Establish unique counter start for category groups
counter = 2000
# Iterate through 'name' groups and assign each one a unique, incremental number
for item in name_groups.groups.keys():
    sb_rel_db.loc[sb_rel_db["name"] == item, ["name_id"]] = counter
    counter +=1
sb_rel_db["name_id"].value_counts()

2003    12
2011    12
2004    12
2024    12
2025    12
2023    12
2010    12
2028    12
2027    12
2005    12
2009    12
2015     9
2007     9
2017     9
2021     9
2013     9
2026     4
2001     4
2002     4
2020     4
2008     4
2022     3
2018     3
2000     3
2016     3
2006     3
2014     3
2012     3
2019     1
Name: name_id, dtype: int64

In [7]:
# Add column for coffee (unique) index numbers
sb_rel_db["sb_id"] = sb_rel_db.index + 1
sb_rel_db.tail()

,category,name,size_oz,milk_type,calories,calories_%dv,caffeine_mg,caffeine_%dv,total_fat_g,fat_%dv,...,sugars_g,sugars_%dv,protein_g,vit_a_%dv,vit_c_%dv,calcium_%dv,iron_%dv,cat_id,name_id,sb_id
214,Signature Espresso Drinks,Caramel Apple Spice (Without Whipped Cream),16,NaN,280,14.0,0,0.0,0.0,0.0,...,65,130.0,0.0,0,0,0,0,1006,2008,215
215,Signature Espresso Drinks,Caramel Apple Spice (Without Whipped Cream),20,NaN,360,18.0,0,0.0,0.0,0.0,...,83,166.0,0.0,0,0,0,0,1006,2008,216
216,Shaken Iced Beverages,Iced Brewed Coffee (With Classic Syrup),12,NaN,60,3.0,120,30.0,0.0,0.0,...,15,30.0,0.0,0,0,0,0,1005,2012,217
217,Shaken Iced Beverages,Iced Brewed Coffee (With Classic Syrup),16,NaN,90,4.0,165,41.0,0.0,0.0,...,21,42.0,0.0,0,0,0,0,1005,2012,218
218,Shaken Iced Beverages,Iced Brewed Coffee (With Classic Syrup),20,NaN,130,6.0,235,59.0,0.0,0.0,...,31,62.0,0.0,0,0,0,0,1005,2012,219

In [18]:
# Create each relational table & export as a .csv file
cat_table = sb_rel_db.filter(["cat_id", "category"], axis = 1)
cat_table.to_csv('cat_table.csv', index = False)

name_table = sb_rel_db.filter(["cat_id", "name_id", "name"], axis = 1)
name_table.to_csv('name_table.csv', index = False)

sb_table = sb_rel_db.filter(["name_id", "sb_id", "size_oz", "milk_type", "calories_%dv", "caffeine_%dv", "fat_%dv", "sugars_%dv"], axis = 1)
sb_table.to_csv('sb_table.csv', index = False)